export const products = [
  {
  id: 1,
  name: "SKINTIFIC 5X Ceramide Low pH Cleanser",
  slug: "skintific-5x-ceramide-cleanser",
  price: 89000,
  stock: 15,
  category: 1,
  category_name: "Skincare",
  rating: 4,
  img: "/images/products/skintificcleanser.jpg",
},
  {
    id: 2,
    name: "SKINTIFIC 10% Niacinamide Brightening Serum",
    slug: "skintific-niacinamide-serum",
    price: 125000,
    stock: 10,
    category: 1,
    category_name: "Skincare",
    rating: 5,
    img: "/images/products/skintificserum.jpg",
  },
  {
    id: 3,
    name: "Azarine Hydrasoothe Sunscreen Gel SPF 45",
    slug: "azarine-hydrasoothe-sunscreen",
    price: 75000,
    stock: 20,
    category: 1,
    category_name: "Skincare",
    rating: 5,
    img: "/images/products/azariness.jpg",
  },
  {
    id: 4,
    name: "SKINTIFIC 5X Ceramide Barrier Moisture Gel",
    slug: "skintific-ceramide-moisture-gel",
    price: 115000,
    stock: 8,
    category: 1,
    category_name: "Skincare",
    rating: 4,
    img: "/images/products/skintificmoist.jpg",
  },
  {
    id: 5,
    name: "Maybelline Superstay Teddy Tint",
    slug: "maybelline-superstay-teddy-tint",
    price: 109000,
    stock: 18,
    category: 2,
    category_name: "Makeup",
    rating: 4,
    img: "/images/products/maybellineteddytint.jpg",
  },
  {
    id: 6,
    name: "Wardah Colorfit Velvet Matte Foundation",
    slug: "wardah-colorfit-velvet-matte-foundation",
    price: 95000,
    stock: 12,
    category: 2,
    category_name: "Makeup",
    rating: 5,
    img: "/images/products/wardahmattefoundi.jpg",
  },
  {
    id: 7,
    name: "L'Oréal Paris Elseve Hyaluron Moisture Shampoo",
    slug: "loreal-elseve-hyaluron-shampoo",
    price: 85000,
    stock: 14,
    category: 3,
    category_name: "Hair Care",
    rating: 4,
    img: "/images/products/lorealshampoo.jpg",
  },
  {
    id: 8,
    name: "Makarizo Hair Energy Fibertherapy Hair Mask",
    slug: "makarizo-hair-energy-hair-mask",
    price: 95000,
    stock: 7,
    category: 3,
    category_name: "Hair Care",
    rating: 5,
    img: "/images/products/makarizohairmask.png",
  },
];